In [1]:
#Q1
import numpy as np38
array = np38.array([[4,6,3],[5,7,3],[9,8,7]])

In [2]:
#Zero Array Q1.1
np38.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [3]:
#Q1.2
print('Element in the second row and third column =', array[1][2])

Element in the second row and third column = 3


In [4]:
#Q1.3
for i in range(3):
    print('Max of Row', i+1, '=', np38.max(array[i]))

Max of Row 1 = 6
Max of Row 2 = 7
Max of Row 3 = 9


In [5]:
#Q1.4
for i in range(3):
    print('Mean of Row', i+1, '=',np38.mean(array[i]))

Mean of Row 1 = 4.333333333333333
Mean of Row 2 = 5.0
Mean of Row 3 = 8.0


In [6]:
#Q1.5
print('Subarray:')
for i in range(2):
    print(array[i])

Subarray:
[4 6 3]
[5 7 3]


In [7]:
#Q2
data = [5, 3, 6, 3, 3, 6, 9, 8, 4, 1]

In [8]:
#Mean
mean = np38.mean(data)
print('Mean =', mean)

Mean = 4.8


In [9]:
#Median
median = np38.median(data)
print('Median =', median)

Median = 4.5


In [10]:
#Mode
count = np38.unique(data, return_counts=True)
index = np38.argmax(count[1])
mode = (count[0])[index]
print('Mode =', mode)

Mode = 3


In [11]:
#Interquartile Range
sorted_data = np38.sort(data)
q1 = np38.percentile(sorted_data, 25)
q3 = np38.percentile(sorted_data, 75)
iqr=q3-q1
print('Interquartile Range =', iqr)

Interquartile Range = 3.0


In [12]:
#Outliers
l_bound = mean - iqr
u_bound = mean + iqr
key = 0
for i in data:
    if(data[i] > u_bound or data[i] < l_bound):
        print("Outlier Exists")
        key = 1
        break
        
if(key==0):
    print("Outlier Does Not Exist")

Outlier Exists


In [13]:
#Q3
import pandas as pd38
column = pd38.DataFrame({"":['Name', 'Age', 'Roll Number']})
print(column.head())

              
0         Name
1          Age
2  Roll Number


In [14]:
#Anagram
string1 = input('String 1: ')
string2 = input('String 2: ')

sort_str1 = sorted(string1)
sort_str2 = sorted(string2)

if(sort_str1 == sort_str2):
    print("Anagram")
else:
    print("Not Anagram")

String 1: listen
String 2: silent
Anagram
